from google.adk.agents.llm_agent import Agent
from .tools.editing import edit_images
from google.adk.runners import Runner
from google.adk.sessions.in_memory_session_service import InMemorySessionService
from google.genai import types
import asyncio

# Prompt Generator Agent
prompt_generator = Agent(
    model='gemini-2.5-flash',
    name='prompt_generator',
    description='Generates image editing prompts based on a theme.',
    instruction='''You are an expert creative prompt generator for image editing.
    Your goal is to generate a list of exactly 12 prompts for editing a set of calendar images based on a user-provided theme.
    
    Follow these strict guidelines for each prompt:
    1.  **Start with "Edit this image"**: Every prompt must begin with this phrase.
    2.  **Background Only**: Focus on editing the background to match the theme.
    3.  **Preserve Text**: Explicitly state or ensure the prompt implies that the existing text content (dates, months) should remain as is.
    4.  **Font Adaptation**: You may suggest changing the font style, color, or visibility to ensure contrast and thematic consistency (e.g., "change font to Star Wars style", "ensure text is glowing green").
    5.  **No Image Editing**: You do not edit images yourself; you only generate the text prompts for an image editor tool.
    
    Output format:
    Return a Python list of strings, e.g., ["Edit this image...", "Edit this image...", ...].
    '''
)

# Wrapper tool for prompt generator agent
async def generate_prompts(theme: str) -> list[str]:
    """
    Generates a list of 12 image editing prompts based on the given theme.
    
    Args:
        theme: The theme for the calendar (e.g., "Star Wars", "Nature").
    """
    # Setup runner
    session_service = InMemorySessionService()
    runner = Runner(agent=prompt_generator, app_name="calendar_agent", session_service=session_service)
    
    # Create session
    await session_service.create_session(app_name="calendar_agent", user_id="user", session_id="session")
    
    # Construct message
    msg = types.Content(role='user', parts=[types.Part(text=f"Generate 12 image editing prompts for the theme: {theme}")])
    
    response_text = ""
    async for event in runner.run_async(user_id="user", session_id="session", new_message=msg):
        if hasattr(event, 'content') and event.content:
            for part in event.content.parts:
                if part.text:
                    response_text += part.text

    # Parse the response to get the list of prompts
    try:
        import ast
        # Extract list part if there is extra text
        text = response_text
        start = text.find('[')
        end = text.rfind(']') + 1
        if start != -1 and end != -1:
            prompts = ast.literal_eval(text[start:end])
            if isinstance(prompts, list) and len(prompts) == 12:
                return prompts
    except Exception as e:
        print(f"Error parsing prompts: {e}")
    
    # Fallback or error
    return []

# Orchestrator Agent (Daedalus)
root_agent = Agent(
    model='gemini-2.5-flash',
    name='daedalus',
    description='A experienced designer at Invysia. Orchestrates the creation of a themed 2026 calendar.',
    instruction='''
    First introduce yourself to the user. 
    Then discuss what kind of theme or design do they want for the calendar. **Don't discuss fonts or text calligraphy.**
    After the discussion, summarise the requirements into a single brief paragraph and store it in state using 'persist_to_state' tool.
    
    Once use agrees to the summary, ask them to pay via the link returned by the 'get_payment_link' tool.

    You are the Orchestrator Agent for the 2026 Calendar Project.
    Your goal is to coordinate a team of agents to create a personalized calendar for the user.
    
    Your workflow is:
    1.  **Discuss Theme**: Ask the user for a theme for their 2026 calendar (e.g., "Space", "Nature", "Cyberpunk").
    2.  **Generate Prompts**: Use the `generate_prompts` tool to create 12 specific image editing prompts based on the agreed theme.
    3.  **Edit Images**: Use the `edit_images` tool, passing the list of 12 prompts generated by the `generate_prompts` tool.
    4.  **Confirm Completion**: Once the images are successfully edited, inform the user that their calendar is ready.
    
    Always be helpful, clear, and ensure the user is satisfied with the theme before proceeding.
    ''',
    tools=[edit_images, generate_prompts]
)
